---

# Install python2
- hosts: all
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tags:
  - python

# Install Docker Engine CS
- hosts: all
  sudo: True
  roles:
  - role: install-engine-cs
  tags:
  - engine

# Install UCP
- hosts: ucp
  sudo: True
  serial: 1
  roles:
  - role: install-ucp
  tags:
  - ucp
  vars:
    ansible_ssh_pipelining: yes

# Install DTR
- hosts: dtr
  sudo: True
  serial: 1
  roles:
  - role: install-dtr
  tags:
  - dtr
