---
- hosts: ddservers
  remote_user: root
  roles:
    - { role: ., sshd: ssh, sshd_config: /etc/sshd_config }
  tasks:
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Add sudoers users to wheel group
    user: name=centos groups=wheel append=yes state=present createhome=yes 
  
  - name: Add SSH key
    authorized_key:
      user: centos
      state: present
      key: "{{ lookup('file', '/path/to/public_key') }}"
  
  - name: Disable empty password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
    
  - name: Disable remote root login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no"
    
  - name: Disable password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  
  - name: Restart sshd service
    service:
      name: sshd
      state: restarted

